# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-11 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
