# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-11 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_stu_age'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cla',
            table='clazz',
        ),
    ]
