# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-11 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180711_1029'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stu',
            table='stu',
        ),
    ]
