# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-11 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180711_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='tea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('clas', models.ManyToManyField(to='myapp.Cla', verbose_name='负责班级')),
            ],
            options={
                'db_table': 'tea',
            },
        ),
    ]
