# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-12 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myappplus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bankcard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='myappplus.BankCard', verbose_name='银行卡'),
        ),
    ]
