# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-13 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacher',
            table='Teacher',
        ),
    ]
