# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-13 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180713_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='salary',
            field=models.IntegerField(db_column='工资', verbose_name='工资'),
        ),
    ]
