# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-10 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180710_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_column='c_name', max_length=20, unique=True, verbose_name='分类名'),
        ),
    ]
